name: Build plugin on push
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: jar
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/build/FishSell-1.0-SNAPSHOT.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
