name: Run Gradle on PRs
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 16
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: jar
          // build/build/FishSell-1.0-SNAPSHOT.jar
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Release
        uses: ridedott/release-me-action@master
        with:
          release-assets: |
            ./build/build/FishSell-1.0-SNAPSHOT.jar